/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/00-localization': RouteRecordInfo<'/00-localization', '/00-localization', Record<never, never>, Record<never, never>>,
    '/01-try': RouteRecordInfo<'/01-try', '/01-try', Record<never, never>, Record<never, never>>,
    '/03-user': RouteRecordInfo<'/03-user', '/03-user', Record<never, never>, Record<never, never>>,
    '/04-partition': RouteRecordInfo<'/04-partition', '/04-partition', Record<never, never>, Record<never, never>>,
  }
}
